name: testing
on: [push, pull_request]
jobs:
  e2e-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - name: "Run Cypress Frontend Tests"
        working-directory: ./frontend
        run: |
          npm install
          npm run e2e:headless
